### ISSUE TITLE
Assignment 7 Question 

### ISSUE THREAD

**Issue by Tao123-debug** [haomateach/cpp#103]
CPSC 1103 (R25) 
Problem: For assignment 7, do we make it so the user can input their information, or we just make information by ourselves?

**Comment by kamalbrar1** [comment]
I think, we are not asked to test the program. So, I am gonna make the program that  allows the user to put/process his information.

**Comment by kartikayprashar** [comment]
@Tao123-debug Also, do we only have to assign values? And do we output anything?

**Comment by gavingro** [comment]
Since it's not specified HOW we are demonstrating our KpuStudent class, I believe it's up to you.

I think figuring out how to demonstrate the different `get()` and `set()` methods is something you're supposed to figure out - we have a bit of freedom here in how we are showcasing our classes.

Using `cin` to get user input to test the program seems like it would fine, but so would defining your own literals to show off the methods. It seems like outputting at least something would be a good idea to show that the class is working, since it would not be clear what is going on without any sort of outputted 'proof'.

**Comment by Tao123-debug** [comment]
Ok, thanks
