### ISSUE TITLE
Github Question

### ISSUE THREAD

**Issue by RAJWINDER19** [haomateach/cpp#17]
Hello everybody, i had just create a repository and folder A1 there but i do not know how to add Q1.ccp and Q2.cpp files for adding code. anyone who can help please reply thanks.

**Comment by haomateach** [comment]
?

**Comment by haomateach** [comment]
1. Please put your question in the issue content rather than the title. 
2. This question has been covered in the Assignment Submission Instruction video on Moodle. Please check it out. 
3. I recommend you to provide screenshots in issues so that we can understand your question better. All you need to do is to drag and release the screenshot onto the issue.
