### ISSUE TITLE
Issue when installing c++ compiler on macOS

### ISSUE THREAD

**Issue by Mohamedismail00** [haomateach/cpp#36]
Hello guys,
I have an issue when installing the c++ compiler on my macOS device. An error message  "Can't install the software because it is not currently available from the software update server" appears. I tried googling the problem but couldn’t find a solution.
If anyone has a solution for this it would be greatly appreciated.
Thanks

**Comment by haomateach** [comment]
Try to attach a screenshot or a link pointing to a video or something, since the current info is not very in detail. 

Have you checked the Section 2 of the udemy course regarding installation?

Don't let this slow down your assignment, you can always use REPL online compiler, please check out our github page.

**Comment by gavingro** [comment]
Hey Mohamed, I had similar problems. I didn't quite figure out what *exactly* was going on, but I found a solution that worked for me.

So on macOS, the easy way to get the C++ compiler we want (so we can compile C++ code) is through Apple's pre-made development tools, which they call Xcode. The instructions in the Udemy video were to try and install it directly from the command line, but they didn't work for me either.

I think that later versions of macOS come with some sort of Xcode something something already, and so when you try to run `xcode-select --install` in the command line, it returns that error you mentioned. Or maybe something is outdated with Xcode-select on apple's update server, or it's renamed - I have no idea, I'm just making uneducated guesses.

But check it out, if you run `xcode-select -p` in the Terminal to look for some Xcode-select on your system and give you the path to the folder, it might even return a file path where something is there. It did for me. I'm not actually sure of the implications of this, like I said, but either way we're going to have to get that Xcode somehow. [This was a helpful stack-overflow post to review](https://stackoverflow.com/questions/19907576/xcode-is-not-currently-available-from-the-software-update-server/19908327#19908327).

Since I couldn't get Xcode from the command line, I looked for answers, and [most](https://developer.apple.com/forums/thread/110552) [sources](https://www.reddit.com/r/MacOS/comments/hf04a4/cant_install_the_software_because_it_is_not/) pointed me towards downloading the [developer tools manually from here](https://developer.apple.com/download/more/?=xcode).

As another option, I imagine if you want you could download the [whole app through the App Store](https://apps.apple.com/us/app/xcode/id497799835?mt=12), but then there will be a whole separate app and IDE that you'll have sitting around, so I don't know if that's ideal. 

Instead, I downloaded the file called "Command Line Tools for Xcode 12" from the [developer tools downloads](https://developer.apple.com/download/more/?=xcode) and installed it. From what I can tell, it doesn't come with the full Xcode app and program, but it does have all the fiddly-bits that let your computer run stuff - including that C++ compiler called *clang*. I think it's just a long way around downloading the Xcode stuff (because we were having trouble downloading that stuff through the terminal).

Not sure if it was overkill, since it was a little bigger than I thought - but *everything was sorted after that*. I could compile and run the code fine after that. 

I'm don't know if you're looking at the same problem as I was, and I really have no clue if there was an easier solution than what I did, but I hope this helps. Either way, stack-overflow will have much better answers than me! Good luck.

**Comment by Mohamedismail00** [comment]
I couldn't be able to install the file called "Command Line Tools for xcode 12" on my mac. Can you please do a screen recording or screenshot of the installation steps if possible

**Comment by Mohamedismail00** [comment]
I followed the steps in the Udemy for the installation and this was the message 
<img width="610" alt="Screen Shot 2020-09-20 at 6 25 34 PM" src="https://user-images.githubusercontent.com/71571901/93727190-dfec4880-fb6e-11ea-9d38-2e126258476d.png">

**Comment by Mohamedismail00** [comment]
Is there any way I can use another compiler online until I fix this issue in order to finish the assignment before its due

**Comment by Mohamedismail00** [comment]
I found a compiler that I need to download from the app store called xcode. Can it be used as my main compiler?

**Comment by Mohamedismail00** [comment]
I couldn't be able to download the "Command Line Tools for Xcode 12" from the developer tools downloads. I found a compiler in the app store called xcode. Can it be used as my main compiler for this course?

**Comment by haomateach** [comment]
@Mohamedismail00 You can use xcode if you want to. Xcode is not a compiler, it's an IDE, just like Codelite. 

If you have trouble installing IDEs, you can temporally use REPL online compiler to complete your assignment 1:

https://repl.it/languages/cpp

You can register yourself an account to save the work.

**Comment by Mohamedismail00** [comment]
Thanks for your help, Will do
