### ISSUE TITLE
"Could not select Compiler" on CodeLite on Mac

### ISSUE THREAD

**Issue by kartikayprashar** [haomateach/cpp#47]
INFO 1112 (R95)

I updated the Xcode app since Frank said keep the app on the latest version. But since then, when I click "Build and Run Project" on CodeLite, it says "compiler not found. Please see the details in the screenshots. Is anyone getting the same issue?

<img width="412" alt="CouldNotSelectCompiler" src="https://user-images.githubusercontent.com/70995067/94322656-efd9a300-ff47-11ea-82eb-df961d9c3cc7.png">
<img width="421" alt="BuildAborted" src="https://user-images.githubusercontent.com/70995067/94322665-f536ed80-ff47-11ea-9b52-212eaf2bdd19.png">

**Comment by kartikayprashar** [comment]
Also, I have tried installing CodeLite again and the additional command line tools, but no luck.

**Comment by kartikayprashar** [comment]
I also looked at the "closed" compiler issue but it didn't solve my problem!

**Comment by haomateach** [comment]
Aside from the 

https://wiki.codelite.org/pmwiki.php/Main/AddNewCompiler


If it still does not work, I recommend you to use **Xcode** instead of Codelite to code C++ on Mac. 

You can search Xcode C++ on youtube to find tons of tutorials on installation instructions. At the same time, don't let the installation stand in the way. You can still use the REPL online compiler to finish the assignment.
