### ISSUE TITLE
struggling with question 20 of assignment 3

### ISSUE THREAD

**Issue by harkamalsingh1** [haomateach/cpp#60]
INFO 1112 S51, anyone has idea how to begin and which course material to look for the solution or any other material which would be helpful in reaching a good solution.

**Comment by gavingro** [comment]
Hey, Hao's linked a resource to the [Docs](http://www.cplusplus.com/reference/string/string/) for string methods that might be a good resource in the related issue #58 .

In terms of problem solving strategies, it's good to plan out how the hell the program is going to work in plain language before you actually start writing in C++. I think this is usually called [Pseudocode](https://www.khanacademy.org/computing/computer-programming/programming/good-practices/pt/planning-with-pseudo-code). There are better explanations out there, but pseudocode is a great way of staying organized in your project. 

I mean, the computer is not going to do the planning for you, but the C++ language is complicated -- the best way to do the planning is just talk through (and write down as comments) what each step of the code is going to be.

For this project your probably going to need to:
1. Read a sentence as input
2. ...
3. Relocate the first letter of each word to the end of the word
4. ...
5. Change the letters of the output string to capitals
6. Print out the string.

This is just taking the steps from the assignment. You can see that these are very broad ideas, but it's a great place to start. I even added in some "..." steps, because you've probably already realized that an input of a sentence may or may not be broken up into words already: for step 2 you might need to "Organize input into list of words" or something, if you think that's the best strategy.

After you have a kind of workflow, you can break down the larger tasks into smaller tasks that you would know how to accomplish in C++. For example, Step 3 could become:

3. Relocate the first letter of the word to the end of the word:
* Find the first letter of the word and assign it to a variable
* Concatenate the first-letter-variable to the end of the word
* Erase the current first of the word.

To avoid plagiarism, I don't want to get much more specific here, but you can see the idea. If you use plain language, you will find it easier to make a plan. Then, with a specific plan, it is easy to translate your "pseudocode" into C++.

That being said, you need to know some different string methods from this week in order to even know that they are an option to use. Hao's link will be a good resource for that.

**Comment by haomateach** [comment]
@gavingro Kudos to such a detailed and well-versed comment!

**Comment by brandonb82** [comment]
@gavingro Yeah i had totally forgotten about pseudocode it definitely helps when you have a plan for what to do before just diving in with not a complete understanding of where to start and what to do first.

**Comment by Gurleen989** [comment]
Actually still I am not getting that like how to do it .......

**Comment by DiljodhNahal** [comment]
> Actually still I am not getting that like how to do it .......
> 
> 

Without giving it away, I'll say that it'll become REALLY easy to do if instead of heading straight into the code, you setup a plan for what you want the code to do.

Take the requirements for the question, and create steps for how you want to convert the sentence into the required output.

Once you have your steps, go through them one by one altering the input as you listed in said steps. Anywhere you get stuck, go back through all the review questions because everything you need is in there.
