### ISSUE TITLE
Q20

### ISSUE THREAD

**Issue by brandonb82** [haomateach/cpp#61]
Info 1112 (S51)
Question regarding Q20.
Are we making a program that we can type any sentence into and it will move the first character to the last position of the word then adding KPU or are we making a program where we assign string with a sentence and then using string code to alter it to the specifications?

**Comment by gavingro** [comment]
Good question.

I think that because it's asking for a sentence as "input", it means we should get input from the user to define the input string. So, this would mean it is the first scenario you described: it could be any sentence made up no non-alphabetic characters. 

The good news is, it shouldn't be a big adjustment between the two methods! Just adjust how you define the string (whether with a string literal or an input stream).

**Comment by brandonb82** [comment]
Thanks just wanted to make sure.

**Comment by haomateach** [comment]
@gavingro Thanks @brandonb82 The former :)
