### ISSUE TITLE
Assessment question 

### ISSUE THREAD

**Issue by Tao123-debug** [haomateach/cpp#68]
CPSC 1103 (R25)
Problem: One of my peer's work is in a "rar" file instead of a zip file, which makes me can't open the file. I wonder if I should mark it a zero.

**Comment by AdrianPrograms** [comment]
The rar format is quite similar to the zip format; they're both equally compressed when you squeeze a file together. The only difference is that rar uses a proprietary algorithm, which means you're going to have to use something like winrar instead of 7zip to extract files.

As for grading, it could fall under the rule of "the zipped file cannot be successfully extracted" which is an automatic 0. I suggest emailing Hao regarding this topic, he might give some leeway with file types.

**Comment by Tao123-debug** [comment]
did Mr. Hao say that it must be a zip file?

**Comment by AdrianPrograms** [comment]
@Tao123-debug 
[I'm referring to the Assignment rubric found here.](https://courses.kpu.ca/pluginfile.php/111739277/mod_resource/content/1/WeeklyAssignmentRubric.pdf)

Under Step 5: "Create a zipped file that only contains files that are relevant to the corresponding
Assignment." **So the file is suppose to be a zip file rather than a rar file.** Though, the instructor comments doesn't specifically say to mark the assignment zero if it's a rar file.

**Comment by gavingro** [comment]
Adding on to what Adrian said - I'm not sure what the actual decision should be.

On the one hand, .rar is also a common file type, but on the other, the instructions clearly say to make sure the file is .zip, but on the other. 

I think it wouldn't be unjustified to give them a 0 if you really can't open it - they didn't follow the instructions and it got in the way of your assessment. At the same time, I'd be choked if I did all the work of the assignment and get a 0 on a technicality.

I'd really wait to see what Hao has to say. That way at least, you don't have to be responsible for making the decision of someone else's grade.

**Comment by Tao123-debug** [comment]
The point is that I can't open the file. I tried, but it wouldn't work.

**Comment by haoma7** [comment]
@Tao123-debug 
7-zip is a free software that can unpack RAR.

https://www.7-zip.org/
