### ISSUE TITLE
CPSC 1103 regarding mid term and quiz 6

### ISSUE THREAD

**Issue by kamalbrar1** [haomateach/cpp#86]
Do we need to watch both chapters 13 and 14 on Udemy, as professor mentioned in course presentation chapter 13 is for midterm and chapter 14 is for quiz #6?

**Comment by gavingro** [comment]
Good eye. You're right, on the syllabus the quiz this week is replaced by the midterm, and we don't touch quiz # 6 until next week. And yet, it's definitely on the moodle for this week.

We'll have to hear what Hao has to say, since we can't check the contents of quiz 6 without "attempting" the quiz.

Just thinking out loud here: I really doubt Hao expects us to double up on sections this week. We already have our midterm this week, and chapter 13 (OOP) is like, twice as long as the other sections already (and they are already lengthy).

My prediction is that quiz # 6 is an additional quiz for this week instead of replacing the midterm, based on this week's contents (13), so that next week's quiz will be about next week (14). Still, it's a bummer that it doesn't match the syllabus perfectly.
